// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        int32
	RecipeID  int32
	UserID    int32
	StartedAt pgtype.Timestamptz
}

type ChatMessage struct {
	ID      int32
	ChatID  int32
	Sender  string
	Message string
	SentAt  pgtype.Timestamptz
}

type Recipe struct {
	ID          int32
	UserID      int32
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type RecipeChunk struct {
	ID         int32
	RecipeID   int32
	ChunkOrder int32
	Content    string
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
